# Tensors

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs af a model, as well as the models parameters.

Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other specialized hardware to accelerate computing.

In [1]:
import torch
import numpy as np

#### Tensor Initialization 

Tensors can be initialized in various ways

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
#### From a NumPy array - Tensors can be created from NumPy arrays and vice versa 
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [5]:
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [6]:
#From another tensor: The new tensor retains the properties(shape, datatype) of the argument tensor, useless explicitily overridden.
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [7]:
x_rand = torch.rand_like(x_data, dtype = torch.float)
x_rand

tensor([[0.0868, 0.4105],
        [0.1618, 0.2187]])

In [8]:
#With random and constant values - 'shape' is a tuple dimensions. In the functions below, it determines the dimensionality of the output tensor
shape = (2, 3,)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.8675, 0.4117, 0.7905],
        [0.2426, 0.5352, 0.7780]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


#### Tensor Attributes 

Tensor attributes desribe their shape, datatype, and the device on which they are stored.

In [9]:
tensor = torch.rand(3, 4)

In [10]:
tensor.shape

torch.Size([3, 4])

In [11]:
tensor.dtype

torch.float32

In [12]:
tensor.device

device(type='cpu')

#### Tensor Operations

Over 100 tensor operations, including transpoing, indexing, slicing, mathematical operations, linear algebra, random sampling and more are somprehensively described

Each of them can be run on the GPU (at typically higher speeds than on a CPU). If you're usin gColab, allocate a GPU by going to

In [13]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    tensor.device

In [14]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
tensor 

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

Joining tensors - You can use `torch.cat` to concatenate a sequence of tensors along a given dimension. And also there is `torch.stack`, another tensor joining op that is subtly different from `torch.cat`

In [15]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

#### Multiplying tensors 
This computes the element-wise product

In [16]:
tensor.mul(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [17]:
#alternative element-wise syntax:
tensor * tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [18]:
# This computes the matrix multiplication between two tensors
tensor.matmul(tensor.T)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [19]:
#Alternative method
tensor@tensor.T

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

#### In-place operations

Operations that have a `_` suffix are in-place. For example: `x.copy_(y)`, `x.t_()` will change `x`.

In [20]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [21]:
tensor.add_(5)
tensor

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

__NOTE__ :

In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history.
Hence there use is discouraged.

# Bridge with NumPy

Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other

#### Tensors to NumPy array

In [22]:
t = torch.ones(5)
t

tensor([1., 1., 1., 1., 1.])

In [23]:
n = t.numpy()
n

array([1., 1., 1., 1., 1.], dtype=float32)

In [24]:
# A change in the tensor reflects numpy array
t.add_(1)
print(t)
print(n)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


#### NumPy array to Tensor

In [25]:
n = np.ones(5)
t = torch.from_numpy(n)

In [26]:
# the changes in the numpy array will reflect in the tensor
np.add(n, 1, out = n)
print(n)
print(t)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# A Gentle Introduction to `touch.autograd`

`torch.autograd` is PyTorch’s automatic differentiation engine that powers neural network training. 

#### Background

Neural networks (NNs) are a collection of nested functions that are executed on some input data. These functions are defined by parameters (consisting of weights and biases), which in PyTorch are stored in tensors.

__Training a NN happens in 2 steps:__

- __Forward Propagation__ : n forward prop, the NN makes its best guess about the correct output. It runs the input data through each of its functions to make this guess.

- __Backward Propagation__ :  In backprop, the NN adjusts its parameters proportionate to the error in its guess. It does this by traversing backwards from the output, collecting the derivatives of the error with respect to the parameters of the functions (gradients), and optimizing the parameters using gradient descent.

#### Usage in PyTorch

Let’s take a look at a single training step. For this example, we load a pretrained resnet18 model from torchvision. We create a random data tensor to represent a single image with 3 channels, and height & width of 64, and its corresponding label initialized to some random values. Label in pretrained models has shape (1,1000).