# Tensors

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs af a model, as well as the models parameters.

Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other specialized hardware to accelerate computing.

In [1]:
import torch
import numpy as np

#### Tensor Initialization 

Tensors can be initialized in various ways

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
#### From a NumPy array - Tensors can be created from NumPy arrays and vice versa 
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [5]:
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [6]:
#From another tensor: The new tensor retains the properties(shape, datatype) of the argument tensor, useless explicitily overridden.
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [7]:
x_rand = torch.rand_like(x_data, dtype = torch.float)
x_rand

tensor([[0.0868, 0.4105],
        [0.1618, 0.2187]])

In [8]:
#With random and constant values - 'shape' is a tuple dimensions. In the functions below, it determines the dimensionality of the output tensor
shape = (2, 3,)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.8675, 0.4117, 0.7905],
        [0.2426, 0.5352, 0.7780]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


#### Tensor Attributes 

Tensor attributes desribe their shape, datatype, and the device on which they are stored.

In [9]:
tensor = torch.rand(3, 4)

In [10]:
tensor.shape

torch.Size([3, 4])

In [11]:
tensor.dtype

torch.float32

In [12]:
tensor.device

device(type='cpu')

#### Tensor Operations

Over 100 tensor operations, including transpoing, indexing, slicing, mathematical operations, linear algebra, random sampling and more are somprehensively described

Each of them can be run on the GPU (at typically higher speeds than on a CPU). If you're usin gColab, allocate a GPU by going to

In [13]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    tensor.device

In [14]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
tensor 

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

Joining tensors - You can use `torch.cat` to concatenate a sequence of tensors along a given dimension. And also there is `torch.stack`, another tensor joining op that is subtly different from `torch.cat`

In [15]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

#### Multiplying tensors 
This computes the element-wise product

In [16]:
tensor.mul(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [17]:
#alternative element-wise syntax:
tensor * tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [18]:
# This computes the matrix multiplication between two tensors
tensor.matmul(tensor.T)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [19]:
#Alternative method
tensor@tensor.T

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

#### In-place operations

Operations that have a `_` suffix are in-place. For example: `x.copy_(y)`, `x.t_()` will change `x`.

In [20]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [21]:
tensor.add_(5)
tensor

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

__NOTE__ :

In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history.
Hence there use is discouraged.

# Bridge with NumPy

Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other

#### Tensors to NumPy array

In [22]:
t = torch.ones(5)
t

tensor([1., 1., 1., 1., 1.])

In [23]:
n = t.numpy()
n

array([1., 1., 1., 1., 1.], dtype=float32)

In [24]:
# A change in the tensor reflects numpy array
t.add_(1)
print(t)
print(n)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


#### NumPy array to Tensor

In [25]:
n = np.ones(5)
t = torch.from_numpy(n)

In [26]:
# the changes in the numpy array will reflect in the tensor
np.add(n, 1, out = n)
print(n)
print(t)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# A Gentle Introduction to `touch.autograd`

`torch.autograd` is PyTorch’s automatic differentiation engine that powers neural network training. 

#### Background

Neural networks (NNs) are a collection of nested functions that are executed on some input data. These functions are defined by parameters (consisting of weights and biases), which in PyTorch are stored in tensors.

__Training a NN happens in 2 steps:__

- __Forward Propagation__ : n forward prop, the NN makes its best guess about the correct output. It runs the input data through each of its functions to make this guess.

- __Backward Propagation__ :  In backprop, the NN adjusts its parameters proportionate to the error in its guess. It does this by traversing backwards from the output, collecting the derivatives of the error with respect to the parameters of the functions (gradients), and optimizing the parameters using gradient descent.

#### Usage in PyTorch

Let’s take a look at a single training step. For this example, we load a pretrained resnet18 model from torchvision. We create a random data tensor to represent a single image with 3 channels, and height & width of 64, and its corresponding label initialized to some random values. Label in pretrained models has shape (1,1000).

In [27]:
import torch 
from torchvision.models import resnet18, ResNet18_Weights

model = resnet18(weights = ResNet18_Weights.DEFAULT)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

In [28]:
#Next, we will run the input data through the model through each of its layers to make a prediction. This is forward pass

prediction = model(data) #forward pass

We use the model’s prediction and the corresponding label to calculate the error (`loss`). The next step is to backpropagate this error through the network. Backward propagation is kicked off when we call `.backward()` on the error tensor. Autograd then calculates and stores the gradients for each model parameter in the parameter’s `.grad` attribute.

In [30]:
loss = (prediction - labels).sum()
loss.backward() # backward pass

In [31]:
optim = torch.optim.SGD(model.parameters(), lr = 1e-2, momentum=0.9)

Finally, we call `.step()` to initiate gradient descent. The optimizer adjusts each parameter by its gradint stored in `.grad`

In [32]:
optim.step() #gradient descent 

At this point, you have everything you need to train your neural network. The below section detail the workings of autograd 

#### Differentiation in Autograd
Let’s take a look at how `autograd` collects gradients. We create two tensors `a` and `b` with `requires_grad=True`. This signals to `autograd` that every operation on them should be tracked.

In [35]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)


We create another tensor `Q` from `a` and `b`

$Q = 3a^3 - b^2$

In [36]:
Q = 3*a**3 - b**2

Let’s assume `a` and `b` to be parameters of a Neural Network (NN), and `Q` to be the error.In NN training, we want gradients of the error with respect to the parameters, i.e.

$$
\frac{\partial Q}{\partial a} = 9a^2
$$

$$
\frac{\partial Q}{\partial b} = -2b
$$


When we call `.backward()` on `Q`, autograd calculates these gradients and stores them in the respective tensors’ `.grad` attribute.

We need to explicitly pass a `gradient` argument in `Q.backward()` because `Q` is a vector.  
`gradient` is a tensor of the same shape as `Q`, and it represents the gradient of `Q` with respect to itself, i.e.

$$
\frac{dQ}{dQ} = 1
$$

Equivalently, we can also aggregate `Q` into a scalar and call backward implicitly, like:

```python
Q.sum().backward()

In [37]:
external_grad = torch.tensor([1., 1.])
Q.backward(gradient = external_grad)

Gradients are now deposited in `a.grad` and `b.grad`

In [38]:
#check if collected gradients are correct

print(9*a**2 == a.grad)
print(-2*b == b.grad)

tensor([True, True])
tensor([True, True])


#### Optional reading - Vector Calculus using `autograd`

Mathematically, if you have a vector-valued function:

$$
\vec{y} = f(\vec{x})
$$

then the gradient of $\vec{y}$ with respect to $\vec{x}$ is a Jacobian matrix $J$:

$$
J =
\begin{pmatrix}
\frac{\partial y_1}{\partial x_1} & \cdots & \frac{\partial y_1}{\partial x_n} \\
\vdots & \ddots & \vdots \\
\frac{\partial y_m}{\partial x_1} & \cdots & \frac{\partial y_m}{\partial x_n}
\end{pmatrix}
$$

Generally speaking, `torch.autograd` is an engine for computing the **vector-Jacobian product**. That is, given any vector:

$$
\vec{v}
$$

compute the product:

$$
J^T \cdot \vec{v}
$$

If $\vec{v}$ happens to be the gradient of a scalar function:

$$
l = g(\vec{y})
$$

then:

$$
\vec{v} =
\begin{pmatrix}
\frac{\partial l}{\partial y_1} \\
\vdots \\
\frac{\partial l}{\partial y_m}
\end{pmatrix}
$$

By the chain rule, the vector-Jacobian product becomes the gradient of $l$ with respect to $\vec{x}$:

$$
J^T \cdot \vec{v}
=
\begin{pmatrix}
\frac{\partial l}{\partial x_1} \\
\vdots \\
\frac{\partial l}{\partial x_n}
\end{pmatrix}
$$

This characteristic of the vector-Jacobian product is what is used in the above example; `external_grad` represents:

$$
\vec{v}
$$

#### Computational Graph
Conceptually, autograd keeps a record of data (tensors) & all executed operations (along with the resulting new tensors) in a directed acyclic graph (DAG) consisting of Function objects. In this DAG, leaves are the input tensors, roots are the output tensors. By tracing this graph from roots to leaves, you can automatically compute the gradients using the chain rule.

In a forward pass, autograd does two things simultaneously:

- run the requested operation to compute a resulting tensor, and
- maintain the operation’s gradient function in the DAG.

The backward pass kicks off when `.backward()` is called on the DAG root. `autograd` then:

- computes the gradients from each `.grad_fn`,
- accumulates them in the respective tensor’s `.grad` attribute, and
- using the chain rule, propagates all the way to the leaf tensors.

Below is a visual representation of the DAG in our example. In the graph, the arrows are in the direction of the forward pass. The nodes represent the backward functions of each operation in the forward pass. The leaf nodes in blue represent our leaf tensors `a` and `b`.

![DAG Representation](image.png)


__NOTE__

DAGs are dynamic in PyTorch An important thing to note is that the graph is recreated from scratch; after each `.backward()` call, autograd starts populating a new graph. This is exactly what allows you to use control flow statements in your model; you can change the shape, size and operations at every iteration if needed.

#### Exclusion from the DAG

`torch.autograd` tracks operations on all tensors which have their `requires_grad` flag set to `True`. For tensors that don’t require gradients, setting this attribute to `False` excludes it from the gradient computation DAG.

The output tensor of an operation will require gradients even if only a single input tensor has `requires_grad=True`.

In [40]:
x = torch.rand(5, 5)
y = torch.rand(5, 5)
z = torch.rand((5, 5), requires_grad = True)

In [41]:
a = x + y
a.requires_grad

False

In [42]:
b = x + z
b.requires_grad

True

In a NN, parameters that don’t compute gradients are usually called frozen parameters. It is useful to “freeze” part of your model if you know in advance that you won’t need the gradients of those parameters (this offers some performance benefits by reducing autograd computations).

In finetuning, we freeze most of the model and typically only modify the classifier layers to make predictions on new labels. Let’s walk through a small example to demonstrate this. As before, we load a pretrained resnet18 model, and freeze all the parameters.

In [43]:
from torch import nn, optim

model = resnet18(weights=ResNet18_Weights.DEFAULT)

# Freeze all the parameters in the network
for param in model.parameters():
    param.requires_grad = False

Let’s say we want to finetune the model on a new dataset with 10 labels. In resnet, the classifier is the last linear layer `model.fc`. We can simply replace it with a new linear layer (unfrozen by default) that acts as our classifier.

In [44]:
model.fc = nn.Linear(512, 10)

Now all parameters in the model, except the parameters of `model.fc`, are frozen. The only parameters that compute gradients are the weights and bias of `model.fc`.

In [45]:
# Optimize only the classifer
optimizer = optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

Notice although we register all the parameters in the optimizer, the only parameters that are computing gradients (and hence updated in gradient descent) are the weights and bias of the classifier.