# Tensors

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs af a model, as well as the models parameters.

Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other specialized hardware to accelerate computing.

In [3]:
import torch
import numpy as np

#### Tensor Initialization 

Tensors can be initialized in various ways

In [10]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [11]:
x_data

tensor([[1, 2],
        [3, 4]])

In [8]:
#### From a NumPy array - Tensors can be created from NumPy arrays and vice versa 
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [9]:
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [12]:
#From another tensor: The new tensor retains the properties(shape, datatype) of the argument tensor, useless explicitily overridden.
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [13]:
x_rand = torch.rand_like(x_data, dtype = torch.float)
x_rand

tensor([[0.4533, 0.8679],
        [0.0581, 0.5501]])

In [15]:
#With random and constant values - 'shape' is a tuple dimensions. In the functions below, it determines the dimensionality of the output tensor
shape = (2, 3,)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.5381, 0.8480, 0.2796],
        [0.4541, 0.4594, 0.4505]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


#### Tensor Attributes 

Tensor attributes desribe their shape, datatype, and the device on which they are stored.

In [17]:
tensor = torch.rand(3, 4)

In [18]:
tensor.shape

torch.Size([3, 4])

In [19]:
tensor.dtype

torch.float32

In [20]:
tensor.device

device(type='cpu')

#### Tensor Operations

Over 100 tensor operations, including transpoing, indexing, slicing, mathematical operations, linear algebra, random sampling and more are somprehensively described

Each of them can be run on the GPU (at typically higher speeds than on a CPU). If you're usin gColab, allocate a GPU by going to

In [21]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    tensor.device

In [22]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
tensor 

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

Joining tensors - You can use `torch.cat` to concatenate a sequence of tensors along a given dimension. And also there is `torch.stack`, another tensor joining op that is subtly different from `torch.cat`

In [26]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

#### Multiplying tensors 
This computes the element-wise product

In [31]:
tensor.mul(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [28]:
#alternative element-wise syntax:
tensor * tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [29]:
# This computes the matrix multiplication between two tensors
tensor.matmul(tensor.T)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [30]:
#Alternative method
tensor@tensor.T

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

#### In-place operations

Operations that have a `_` suffix are in-place. For example: `x.copy_(y)`, `x.t_()` will change `x`.

In [32]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [33]:
tensor.add_(5)
tensor

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

__NOTE__ :

In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history.
Hence there use is discouraged.